// Labeled calibration corpus for the local detector.
//
// "ai" samples imitate assistant-drafted YouTube narration (explainers, listicles,
// faceless-channel voiceovers). "human" samples imitate spontaneous or hand-written
// speech: vlogs, gameplay, podcasts, lectures, and tutorials, including creators who
// use ordinary YouTube intros and calls to action.
//
// These are synthetic stand-ins for real transcripts. They exist to catch regressions
// in separation, not to prove accuracy on real videos.

const AI_SAMPLES = [
  {
    id: "ai-productivity",
    text: `In today's fast-paced world, staying productive can feel like an uphill battle. But what if there was a better way? In this video, we'll explore five powerful habits that can transform the way you work. Let's dive in. First and foremost, it's essential to prioritize your tasks. By focusing on what truly matters, you can unlock your full potential and achieve more in less time. Moreover, creating a structured routine helps you navigate the challenges of a busy schedule with ease. Second, embrace the power of deep work. Deep work allows you to harness your focus and produce high-quality results. It's important to note that distractions are the enemy of progress. Furthermore, taking regular breaks can actually boost your productivity rather than hinder it. Third, leverage technology wisely. From task managers to calendar apps, the right tools can streamline your workflow and help you stay on track. Additionally, setting clear goals gives you a roadmap for success. In conclusion, productivity isn't just about working harder; it's about working smarter. Whether you're a student, a professional, or an entrepreneur, these habits can help you thrive in an ever-evolving landscape. Remember, the journey of a thousand miles begins with a single step. If you found this video helpful, don't forget to like, subscribe, and hit the notification bell for more content like this.`
  },
  {
    id: "ai-history",
    text: `Throughout history, few empires have captured the imagination quite like ancient Rome. Nestled along the banks of the Tiber River, this remarkable civilization rose from humble beginnings to become one of the most powerful forces the world has ever known. But how did it all begin? Let's delve into the fascinating story of Rome's rise to power. The Roman Republic was a testament to the ingenuity of its people. With a complex system of checks and balances, it laid the foundation for modern democratic institutions. Moreover, Rome's military prowess played a pivotal role in its expansion. Its legions were known for their discipline, innovation, and unwavering loyalty. However, it wasn't just military might that made Rome great. The empire's rich tapestry of culture, art, and architecture continues to inspire us today. From the majestic Colosseum to the intricate network of roads, Rome's legacy stands the test of time. Furthermore, Roman law has left an indelible mark on legal systems around the world. Ultimately, the story of Rome serves as a powerful reminder of both the heights of human achievement and the fragility of even the greatest empires. As we reflect on this incredible journey, one thing is clear: the echoes of Rome still resonate in the modern world. Thank you for joining us on this journey through history.`
  },
  {
    id: "ai-finance",
    text: `Are you tired of living paycheck to paycheck? You're not alone. Millions of people struggle to manage their finances effectively. But the good news is that with the right strategies, you can take control of your financial future. In this video, we'll break down seven essential money tips that can change your life. Tip number one: create a budget. A budget is the cornerstone of financial success. It empowers you to track your spending and identify areas where you can save. Tip number two: build an emergency fund. Life is unpredictable, and having a safety net can provide peace of mind. Experts generally recommend saving three to six months of expenses. Tip number three: pay off high-interest debt. Debt can be a significant obstacle on your path to financial freedom. By tackling it strategically, you can free up more resources for your goals. Tip number four: invest in your future. Investing may seem intimidating, but it's a crucial step in building long-term wealth. Tip number five: automate your savings. Automation takes the guesswork out of saving and ensures consistency. It's worth noting that small changes can lead to big results over time. Remember, financial freedom is not a destination; it's a journey. By implementing these strategies, you'll be well on your way to a brighter, more secure future. So what are you waiting for? Start today.`
  },
  {
    id: "ai-travel",
    text: `Welcome to Lisbon, a vibrant city where history and modernity blend seamlessly. Nestled on the banks of the Tagus River, Portugal's charming capital offers a unique blend of culture, cuisine, and breathtaking views. Whether you're a history buff, a foodie, or an adventurer, Lisbon has something for everyone. Let's explore the hidden gems that make this city truly unforgettable. First, wander through the enchanting streets of Alfama, the city's oldest neighborhood. Here, narrow cobblestone alleys and colorful houses create a captivating atmosphere that transports you back in time. Next, immerse yourself in the rich tapestry of flavors at the bustling Time Out Market. From fresh seafood to the iconic pastel de nata, your taste buds are in for a treat. Moreover, no visit would be complete without a ride on the historic Tram 28. This iconic journey offers a glimpse into the heart and soul of the city. As the sun sets, head to one of Lisbon's many viewpoints and witness a truly magical experience. In essence, Lisbon is a destination that captures the heart and leaves a lasting impression. It's not just a city; it's an experience waiting to be discovered. So pack your bags and embark on an adventure you'll never forget.`
  },
  {
    id: "ai-science",
    text: `Have you ever wondered why the sky is blue? It's a question that has fascinated curious minds for centuries. In today's video, we're going to uncover the science behind this everyday phenomenon. Let's get started. The answer lies in a process called Rayleigh scattering. When sunlight enters Earth's atmosphere, it interacts with molecules of gas. Sunlight is made up of a spectrum of colors, each with a different wavelength. Shorter wavelengths, like blue and violet, are scattered more effectively than longer wavelengths, like red and orange. This is why we see a blue sky during the day. But wait, if violet light has an even shorter wavelength, why isn't the sky violet? That's a great question. The answer is that our eyes are more sensitive to blue light, and some violet light is absorbed high in the atmosphere. Furthermore, this same process explains the stunning colors of a sunset. As the sun dips lower, its light travels through more of the atmosphere, scattering away the blue and leaving warm reds and oranges. Isn't that fascinating? In summary, the blue sky is a beautiful reminder of the intricate interplay between light and matter. Understanding these natural wonders helps us appreciate the world around us. If you enjoyed this video, be sure to subscribe and stay curious.`
  },
  {
    id: "ai-motivation",
    text: `Success doesn't happen overnight. It's the result of consistent effort, unwavering determination, and a mindset that refuses to give up. In this video, we'll explore the key principles that separate those who succeed from those who don't. Let's dive deep. First, it all starts with a growth mindset. When you believe that your abilities can be developed, you open the door to endless possibilities. Challenges become opportunities, and failures become valuable lessons. Second, discipline is the bridge between goals and accomplishment. Motivation may get you started, but discipline keeps you going when the going gets tough. Moreover, surrounding yourself with the right people can make all the difference. The people you spend time with shape your thoughts, your habits, and ultimately your future. Third, embrace discomfort. Growth happens outside your comfort zone. It's in those moments of struggle that you discover what you're truly capable of. Additionally, never underestimate the power of small wins. Every step forward, no matter how small, brings you closer to your dreams. At the end of the day, the only thing standing between you and your goals is the story you keep telling yourself. Remember, you have the power to rewrite that story. Believe in yourself, stay focused, and never give up. Your future self will thank you.`
  },
  {
    id: "ai-tech-review",
    text: `The smartphone market is more competitive than ever, and this latest flagship aims to stand out from the crowd. But does it live up to the hype? In this comprehensive review, we'll take a closer look at its design, performance, camera, and battery life to help you decide if it's the right choice for you. Let's dive in. Right out of the box, the design is sleek and premium. The device feels solid in the hand, and the attention to detail is truly impressive. Moreover, the vibrant display delivers stunning colors and deep contrast, making it perfect for streaming, gaming, and everyday use. When it comes to performance, this phone doesn't disappoint. Powered by a cutting-edge processor, it handles multitasking with ease and delivers a seamless user experience. Additionally, the camera system is a game changer. Whether you're capturing breathtaking landscapes or low-light portraits, the results are consistently impressive. Battery life is another standout feature. With intelligent power management, the device easily lasts a full day of heavy use. However, it's important to note that the price may be a barrier for some users. Overall, this smartphone offers an exceptional blend of style, power, and innovation. If you're looking for a premium device that elevates your mobile experience, it's definitely worth considering. Let us know your thoughts in the comments below.`
  },
  {
    id: "ai-mystery",
    text: `In the quiet town of Millbrook, nestled deep in the heart of the countryside, a mystery unfolded that would baffle investigators for decades. On a cold autumn night, a young woman vanished without a trace, leaving behind a community shrouded in fear and uncertainty. What happened that night remains one of the most chilling unsolved cases of our time. As the investigation unfolded, detectives uncovered a web of secrets that sent shockwaves through the tight-knit community. Witnesses reported strange lights in the woods, while others spoke of a mysterious figure seen lurking near the old mill. Moreover, a series of cryptic letters began arriving at the local police station, each one more unsettling than the last. Despite countless leads and tireless efforts, the case eventually went cold. However, the story doesn't end there. Years later, a shocking discovery would reignite the investigation and raise even more questions. Was it a tragic accident, a carefully planned crime, or something far more sinister? To this day, the truth remains shrouded in mystery. The haunting tale of Millbrook serves as a stark reminder that some secrets are never meant to be uncovered. What do you think happened? Let us know your theories in the comments, and don't forget to subscribe for more unsolved mysteries.`
  },
  {
    id: "ai-cooking",
    text: `There's nothing quite like the comforting aroma of freshly baked bread filling your kitchen. In today's video, we're going to walk you through a simple yet delicious homemade bread recipe that's perfect for beginners. Whether you're a seasoned baker or just starting out, this recipe is sure to impress. Let's get started. First, gather your ingredients. You'll need flour, water, yeast, salt, and a touch of sugar. It's important to use high-quality ingredients, as they play a crucial role in the final result. Next, activate the yeast by combining it with warm water and sugar. This step is essential for achieving that perfect rise. Once the mixture becomes frothy, it's time to combine it with the flour and salt. Knead the dough until it's smooth and elastic. This process develops the gluten, which gives the bread its wonderful texture. Moreover, patience is key during the rising process. Allow the dough to rest in a warm place until it has doubled in size. Finally, shape the loaf and bake it until it's golden brown and sounds hollow when tapped. The result is a beautiful loaf with a crisp crust and a soft, fluffy interior. In conclusion, homemade bread is not only delicious but also incredibly rewarding. Give this recipe a try and elevate your baking game. Happy baking!`
  }
];

const HUMAN_SAMPLES = [
  {
    id: "human-flea-market-vlog",
    text: `Okay so um today we're gonna be looking at this thing I found at the flea market last weekend, and honestly I had no idea what it was when I bought it. The guy wanted like twenty bucks and I talked him down to twelve. So I get it home, and my wife is like, what is that, and I'm like, I don't know, that's the point. Anyway I took it apart in the garage and there's this weird little spring inside that I've never seen before, it's kind of bent at a funny angle. So I called my buddy Mike who used to fix sewing machines and he said it might be part of an old treadle mechanism. Which, fine, maybe. But then why is there a date stamped on it from 1962? That doesn't line up at all, the treadle stuff he's talking about is way older. I also found these two little brass screws that don't match anything else on it, like somebody repaired it at some point with whatever they had lying around. So yeah. Let me know in the comments if you've seen one of these before because I'm stumped. And if it's something dumb like a part off a lawnmower, please be gentle.`
  },
  {
    id: "human-gaming",
    text: `Alright we're back, we're back. So last episode I lost basically everything in the lava, which, not my proudest moment. Okay so the plan today is get iron, like a full stack if we can, and then maybe get back to that village before it gets dark. Oh there's a cave right there, okay, okay. Wait is that, no that's gravel. Why is it always gravel. Chat is saying go left, fine, going left. Oh no. Oh no no no, there's like three creepers down here. I have four hearts, I have four hearts, this is fine. Okay I'm just gonna, I'm gonna back up. Nope. Nope. That was so close, did you hear that? My heart is actually pounding right now, I'm not even joking. Okay iron, there's iron right there, look at that, one, two, like six blocks. Somebody in chat just said I play like their grandma and honestly that's fair. Let me just put a torch down so I can find my way out, because last time I got lost for like twenty minutes and it was embarrassing. Alright, that's a good haul. I'm gonna end it here before I do something stupid again. Thanks for hanging out, see you guys tomorrow.`
  },
  {
    id: "human-podcast",
    text: `Yeah, so the thing I keep coming back to is, when we started the shop in 2017, we had no idea what we were doing with inventory. Right, you told me you had like a garage full of boxes. Oh it was bad. It was so bad. My dad would come over and just, he'd stand there looking at it and shake his head. And the first holiday season we sold out of the green mugs in like four days and we had two hundred of the brown ones nobody wanted. Which, to be fair, the brown ones were ugly. They were ugly! I'll own that. But the lesson was, I was ordering based on what I liked, not what people were buying. So what changed? Honestly a spreadsheet. Just a dumb spreadsheet, every Sunday night, what sold, what didn't. Took me maybe an hour. And after like three months I could kind of see it. Like, people buy mugs in October, they buy the little plant pots in March, nobody buys anything the week after Christmas. That makes sense. And then Jess, who you know, she came in part time and she was way better at it than me, so I just handed it off. Best decision I made that year, probably. Probably. Other than the brown mugs. We're never going to let that go, are we. No. Never.`
  },
  {
    id: "human-lecture",
    text: `The Krebs cycle takes place in the mitochondrial matrix. Acetyl-CoA combines with oxaloacetate to form citrate, which is then isomerized to isocitrate. Isocitrate dehydrogenase catalyzes an oxidative decarboxylation, producing alpha-ketoglutarate and the first NADH of the cycle. Alpha-ketoglutarate is decarboxylated again, yielding succinyl-CoA and a second NADH. Succinyl-CoA synthetase generates GTP by substrate-level phosphorylation. Succinate is oxidized to fumarate by succinate dehydrogenase, which is embedded in the inner membrane and passes electrons to FAD. Fumarate is hydrated to malate, and malate is oxidized back to oxaloacetate, producing a third NADH. Per turn, then, we get three NADH, one FADH2, one GTP, and two molecules of carbon dioxide. Now, a question I get every year: if the cycle regenerates oxaloacetate, why do cells ever run short of it? The answer is that intermediates get pulled off for biosynthesis. Citrate leaves for fatty acid synthesis, alpha-ketoglutarate feeds glutamate, and so on. Pyruvate carboxylase tops the pool back up. That's called an anaplerotic reaction, and it will be on the midterm, so write that down. For Thursday, read sections 17.3 and 17.4, and bring questions about the electron transport chain, because we're starting that next week.`
  },
  {
    id: "human-diy",
    text: `So what I'm doing here is I'm taking the old baseboard off, and you want to go slow because this is original to the house and it's like 1940s pine and it splits if you look at it wrong. I'm using a five-in-one, just get it behind there, little bit at a time. See, there's the caulk line, I'm gonna score that first with a utility knife. Okay. Now it's coming. You hear that? That's the old cut nails, they're square, you can't really reuse them. I'll pull them through the back with nippers so I don't blow out the face. Right, so this piece is about nine feet, and I'm gonna label the back with a pencil, like A1, so I know where it goes back. Learned that one the hard way on the last house, had like fourteen pieces and no idea which wall they came from. Behind here you can see the plaster just stops about half an inch above the floor, that's normal, don't panic if you see that. What's not normal is this, see this dark spot? That's old water damage from a radiator that used to sit here, it's dry now, I checked it with the moisture meter, it's reading eleven percent, so we're fine. Okay next piece.`
  },
  {
    id: "human-cooking",
    text: `Okay, so this is my grandmother's recipe, more or less, she never wrote anything down so this is me trying to remember what she did. Two cups of flour, and I'm using the King Arthur because that's what I had. She definitely used whatever was cheapest. Pinch of salt. Now the butter has to be really cold, like I put it in the freezer for fifteen minutes, because if it's soft you get this greasy crust and it's just sad. I'm grating it in, which is a trick I got from a friend, it's way easier than cutting it in with two knives. Look at that. Okay, ice water, a tablespoon at a time. You really want to stop before it looks done, it should still be kind of shaggy. See how it's barely holding together? That's it, that's what you want. My first few tries I added way too much water and it came out tough, like a cracker. Wrap it up, into the fridge for at least an hour, overnight is better honestly. While that's chilling I'm gonna do the apples. I'm using Honeycrisp and a couple of Granny Smiths, my grandmother used whatever was on the tree in the backyard, which I think was McIntosh, and they turn to mush, but she liked it that way.`
  },
  {
    id: "human-tech-review",
    text: `I've been using this phone for about three weeks now as my only phone, so this isn't an unboxing, this is how it actually held up. Battery first because that's what everyone asks about. On a normal day for me, which is Slack, maps in the car, maybe an hour of YouTube, I was ending at around thirty percent. On the day I flew to Denver I killed it by four in the afternoon, but I was tethering my laptop for like two hours, so that's on me. The camera is good in daylight. Indoors it's weird, it keeps brightening faces way too much, my kid looks like she's lit by a ring light in every photo, and there's no way to turn that off that I could find. I filed a bug report, we'll see. The screen is great, no complaints. The thing that actually annoyed me the most is the fingerprint reader, it's placed really low, and I kept hitting the volume button instead. Small thing, but I unlock my phone like a hundred times a day. Is it worth nine hundred dollars? If you're coming from something three or four years old, yeah, probably. If you have last year's model, I would not bother, the differences are really small.`
  },
  {
    id: "human-creator-cta",
    text: `Hey guys, welcome back to the channel. If you're new here, I'm Dana and I restore old bikes. Today we're going to look at this 1984 Peugeot I picked up from a guy in Leeds for forty quid, and let me tell you, the photos did not show the rust. Look at the chainstay. Just look at it. So the first thing I always do is check the frame for cracks, especially around the bottom bracket, because if the frame's cracked it's scrap and I'm out forty quid. Okay. No cracks, that I can see. Good. The paint is shot but that's fine, I wasn't going to keep it anyway. The rear derailleur is a Simplex, which, if you know you know, they're plastic and they snap if you breathe on them. This one is actually working, which is kind of a miracle. Wheels are the original Mavic rims and they're a bit out of true, I'll sort that on the stand. Tyres are completely perished, they're cracking all along the sidewall, so those are going in the bin. Right, that's the teardown done. Next week we'll strip the frame and I'll show you how I deal with rust in the tubes. If you enjoyed this, give it a like and subscribe, it really does help the channel, and let me know in the comments what you'd want me to restore next.`
  },
  {
    id: "human-news-explainer",
    text: `The city council voted six to three on Tuesday night to approve the new bus lanes on Harrison Avenue, after almost four hours of public comment. I was there for most of it. The biggest concern from business owners was parking. Right now there are about forty metered spots along the stretch between Fifth and Twelfth, and the plan removes twenty-six of them. Maria Delgado, who owns the bakery on the corner of Ninth, told the council her Saturday sales drop by about a third whenever the street is torn up, and she's worried this will be permanent. On the other side, the transit agency says the 22 bus, which runs that corridor, is late about forty percent of the time during the evening rush, mostly because it gets stuck behind turning traffic. They're projecting the lanes cut about six minutes off the trip. Councilmember Park, who voted no, said she supports the goal but wanted a six-month pilot first, and honestly that seemed like the compromise a lot of people in the room were waiting for. Construction is supposed to start in March. I'll be checking back with Maria and a couple of the other shops once it's in, and we'll see whether those numbers hold up.`
  }
];

// Samples written after the detector was tuned on the sets above and scored
// without further tuning. Keep them as a held-out check: if a change only helps
// the sets above, these will show it.
const HELD_OUT_AI_SAMPLES = [
  {
    id: "ai-octopus",
    text: `Octopuses are some of the most intelligent creatures on the planet, and today we're counting down five mind-blowing facts that will change the way you see them. Number five: octopuses have three hearts. Two hearts pump blood to the gills, while the third circulates it to the rest of the body. Number four: their blood is blue. This is due to a copper-rich protein called hemocyanin, which is more efficient at transporting oxygen in cold, low-oxygen environments. Number three: they are masters of disguise. Using specialized cells called chromatophores, octopuses can change both the color and texture of their skin in a fraction of a second. Number two: each arm has a mind of its own. In fact, around two-thirds of an octopus's neurons are located in its arms, allowing each one to taste, touch, and react independently. And number one: octopuses are incredible problem solvers. They have been observed opening jars, escaping aquariums, and even using coconut shells as portable shelters. These remarkable abilities make the octopus a true marvel of the natural world. Which fact surprised you the most? Let us know in the comments, and don't forget to subscribe for more amazing animal facts.`
  },
  {
    id: "ai-sports",
    text: `The 1980 Winter Olympics in Lake Placid delivered one of the most unforgettable moments in sports history. It was a story of determination, teamwork, and the triumph of the underdog. Few gave the young American hockey team, made up largely of college players, any chance against the mighty Soviet Union. The Soviets had dominated international hockey for years, boasting a lineup of seasoned professionals. However, under the leadership of coach Herb Brooks, the Americans had something special: unwavering belief. As the game unfolded, the energy in the arena was electric. Trailing for much of the contest, the Americans refused to give up. Then, in the third period, team captain Mike Eruzione fired the go-ahead goal, sending the crowd into a frenzy. For the final ten minutes, the Americans held on with incredible resilience. As the clock ticked down, broadcaster Al Michaels delivered his iconic call: do you believe in miracles? Yes! The Miracle on Ice was more than just a hockey game; it was a symbol of hope and national pride during a challenging time. Decades later, its legacy continues to inspire athletes and fans around the world, reminding us that with heart and determination, anything is possible.`
  },
  {
    id: "ai-casual-firstperson",
    text: `Hey everyone! So today I wanted to share something that has completely changed my morning routine. A few months ago, I was constantly feeling tired and unmotivated. I knew something had to change. That's when I discovered the power of journaling. At first, I was skeptical. I mean, how could writing a few sentences each morning make a difference? But I decided to give it a try, and honestly, I'm so glad I did. Every morning, I spend just ten minutes writing down three things I'm grateful for and my main goals for the day. It sounds simple, but it has made a huge impact on my mindset. I feel more focused, more positive, and more in control of my day. Not only that, but journaling has also helped me become more aware of my thoughts and emotions. It's like having a conversation with myself. If you're looking for a small habit that can make a big difference, I highly recommend giving journaling a try. Trust me, your future self will thank you. Let me know in the comments if you journal or if you're going to start. And as always, thanks for watching!`
  },
  {
    id: "ai-specific-product",
    text: `The new Aurora X2 air purifier is designed to deliver clean, fresh air to spaces up to 1,200 square feet. Equipped with a true HEPA H13 filter, it captures 99.97 percent of airborne particles as small as 0.3 microns, including dust, pollen, and pet dander. Moreover, an activated carbon layer helps eliminate odors from cooking, smoke, and everyday life. One standout feature is its intelligent air quality sensor. The device continuously monitors your environment and automatically adjusts fan speed to maintain optimal air quality. Additionally, the sleek, minimalist design blends seamlessly into any room. With a noise level as low as 22 decibels in sleep mode, it's perfect for bedrooms and nurseries. The companion app allows you to control settings remotely, schedule operation, and track filter life in real time. Energy efficiency is another key benefit, as the Aurora X2 consumes just 45 watts on its highest setting. Overall, the Aurora X2 offers an exceptional combination of performance, convenience, and style. Whether you're dealing with allergies or simply want a healthier home, it's a smart investment in your well-being.`
  }
];

const HELD_OUT_HUMAN_SAMPLES = [
  {
    id: "human-documentary-script",
    text: `The first thing you notice about the salt marsh at low tide is the smell. It is not unpleasant, exactly, but it is thick, a mix of rotting cordgrass and mud that has been sealed off from the air for most of the day. Twice a day the Atlantic floods this place and twice a day it drains away, and everything that lives here has had to make some arrangement with that rhythm. Fiddler crabs, for instance, spend the high tide in burrows they plug with a pellet of mud, and they come out only when the water leaves. The males wave one oversized claw at each other and at any female who wanders past. Biologists spent decades assuming the display was purely about attracting mates. It turns out it is also a kind of border patrol: a male who waves more often holds his patch of mud longer. Out on the open flats, a willet works the edge of a creek, probing for worms. It will fly four thousand miles this year. The marsh, which looks empty from the road, is in fact one of the most productive places on the coast, gram for gram more productive than a cornfield. We drained about half of them in the last century before anyone noticed.`
  },
  {
    id: "human-video-essay",
    text: `I want to talk about why every new apartment building in my city looks the same. You know the ones. Ground floor retail that nobody rents, four or five storeys of wood frame on top, a panel facade in two or three colors, usually grey and some kind of orange. People call them gentrification boxes, which I think is a bit unfair, but I get it. The reason they look like this is mostly the building code. Since 2009 the code here lets you build up to five storeys of wood on top of one storey of concrete, and anything taller than that means switching the whole structure to concrete or steel, which roughly doubles the cost per square foot. So developers stop at exactly that height, every time. The panels are cheap and fast, and the colors, as far as I can tell, are because a developer once told me beige doesn't photograph well. I'm not saying these buildings are good. I actually don't like most of them. But I think it's more useful to be annoyed at the code than at the architects, because the architects are working inside a box, pretty literally, that somebody else drew.`
  },
  {
    id: "human-interview",
    text: `So how did you end up running the ferry? Oh, by accident, really. My uncle ran it for thirty-one years and when his knees went, nobody else in the family wanted it. I was working at the co-op at the time, stocking shelves. I said I'd do it for one summer until they found somebody. That was 2006. What's the hardest part? Honestly, it's the fog. People think it's the winter, and the winter's bad, don't get me wrong, we had ice on the ramp last February that took two days to chip off. But fog, you can't do anything about fog. You slow down, you use the radar, you listen. There was one morning, I think it was August, I had a school group on board, twenty-some kids, and I couldn't see the bow from the wheelhouse. Took us fifty minutes to do a twelve-minute crossing. The teacher was white as a sheet. The kids thought it was the best thing ever. Would you do it again? Every day. I mean, I complain about it constantly, ask my wife. But yeah. Every day.`
  },
  {
    id: "human-sermon-talk",
    text: `I've been thinking this week about my grandfather's hands. He was a carpenter, and by the time I knew him, he was missing the tip of his left index finger from a table saw accident in 1961. He never talked about it. When I asked, he'd just hold it up and say, that one's on loan. What I remember most is how slowly he did everything. He'd measure a board three times. He'd sand a drawer until it closed with this little puff of air, and then he'd open it and close it again, just to hear it. My brother and I thought he was the most patient man alive. Years later my grandmother told us he had a terrible temper when he was young, that he'd thrown a hammer through a window more than once. The patience was something he built, the same way he built everything else, one careful pass at a time. I don't have his patience. Some of you know that about me. But I've started, when I catch myself rushing, to think about that drawer and that little puff of air. And I slow down. Most days.`
  }
];

// Mimic how YouTube caption tracks arrive: short timed lines joined with newlines.
function toCaptionLines(text, { wordsPerLine = 8, stripPunctuation = false } = {}) {
  let source = text;
  if (stripPunctuation) {
    source = source
      .toLowerCase()
      .replace(/[.,;:!?]/g, "")
      .replace(/\bi\b/g, "I");
  }
  const words = source.split(/\s+/).filter(Boolean);
  const lines = [];
  for (let index = 0; index < words.length; index += wordsPerLine) {
    lines.push(words.slice(index, index + wordsPerLine).join(" "));
  }
  return lines.join("\n");
}

module.exports = {
  AI_SAMPLES,
  HUMAN_SAMPLES,
  HELD_OUT_AI_SAMPLES,
  HELD_OUT_HUMAN_SAMPLES,
  toCaptionLines
};
