(function (root) {
  const App = (root.AIScriptDetector = root.AIScriptDetector || {});

  App.patterns = {
    scriptIntroPhrases: [
      "in today's video",
      "in this video",
      "today we're going to",
      "today i want to",
      "let's dive in",
      "without further ado",
      "here's why",
      "we're going to break down",
      "let's get into it",
      "today we'll cover",
      "welcome back to the channel",
      "before we get started",
      "if you've ever wondered",
      "watch until the end",
      "today i'm going to show you",
      "in this script",
      "in this breakdown"
    ],
    callToActionPhrases: [
      "like and subscribe",
      "hit that subscribe button",
      "leave a comment",
      "drop a comment",
      "thanks for watching",
      "follow for more",
      "stay tuned",
      "see you in the next one",
      "let me know what you think",
      "smash the like button",
      "subscribe to the channel",
      "ring the bell",
      "comment below",
      "share this video"
    ],
    recapPhrases: [
      "to recap",
      "in summary",
      "the bottom line",
      "the key takeaway",
      "wrapping up",
      "in conclusion",
      "all in all",
      "to sum it up"
    ],
    youtubePackagingPhrases: [
      "and now",
      "or die",
      "one by one",
      "while they try to",
      "find a way to stop",
      "find a way to survive",
      "find a way to escape",
      "forced to",
      "must survive",
      "must escape",
      "must pass",
      "before it's too late",
      "movie recap",
      "film recap",
      "story recap",
      "ending explained",
      "plot summary",
      "explained in minutes",
      "tries to survive",
      "has to survive"
    ],
    highStakesTerms: [
      "must",
      "die",
      "death",
      "survive",
      "escape",
      "killer",
      "kill",
      "killed",
      "cursed",
      "curse",
      "trapped",
      "forced",
      "haunted",
      "demise",
      "chased",
      "before"
    ],
    titleHookRegexes: [
      /\b(?:he|she|they)\b[\w\s,'-]{0,80}\band now\b[\w\s,'-]{0,80}\b(?:must|has to|needs to|is forced to)\b/i,
      /\b(?:must|has to|needs to|is forced to)\b[\w\s,'-]{0,60}\b(?:or die|to survive|before it's too late)\b/i,
      /\b(?:one by one|while they try to|find a way to (?:stop|survive|escape)|future demise)\b/i
    ],
    transitionPhrases: [
      "moreover",
      "furthermore",
      "additionally",
      "however",
      "therefore",
      "overall",
      "ultimately",
      "meanwhile",
      "in addition",
      "for example",
      "on the other hand",
      "as a result",
      "that said",
      "with that in mind"
    ],
    genericPhrases: [
      "it is important to note",
      "plays a crucial role",
      "in today's fast-paced world",
      "game changer",
      "take it to the next level",
      "across the board",
      "unlock the potential",
      "wide range of",
      "various aspects of",
      "for businesses and individuals alike",
      "from start to finish",
      "at the end of the day",
      "when it comes to",
      "one of the most important things",
      "the good news is",
      "the reality is",
      "you won't believe",
      "this is huge",
      "everything you need to know",
      "the secret to",
      "what most people don't realize"
    ],
    vagueTerms: [
      "various",
      "numerous",
      "significant",
      "innovative",
      "effective",
      "powerful",
      "robust",
      "seamless",
      "valuable",
      "meaningful",
      "dynamic",
      "transformative",
      "insightful",
      "remarkable",
      "comprehensive",
      "notable",
      "key",
      "crucial",
      "important",
      "impactful",
      "relevant",
      "helpful",
      "useful"
    ],
    hedgeTerms: [
      "generally",
      "often",
      "typically",
      "usually",
      "in many ways",
      "can help",
      "can improve",
      "may lead to",
      "tends to",
      "in some cases",
      "for many people",
      "in a lot of cases",
      "the truth is",
      "chances are"
    ],
    businessBuzzwords: [
      "solution",
      "strategy",
      "leverage",
      "optimize",
      "synergy",
      "landscape",
      "ecosystem",
      "framework",
      "scalable",
      "streamline",
      "efficiency",
      "stakeholders",
      "workflow",
      "alignment",
      "competitive",
      "engagement",
      "growth",
      "outcomes",
      "value",
      "audience",
      "content",
      "best practices"
    ],
    abstractTerms: [
      "innovation",
      "impact",
      "value",
      "growth",
      "efficiency",
      "strategy",
      "success",
      "potential",
      "approach",
      "process",
      "experience",
      "solution",
      "insight",
      "opportunity",
      "challenge",
      "benefit",
      "vision",
      "trend",
      "industry",
      "audience",
      "journey",
      "landscape",
      "improvement",
      "result",
      "outcome"
    ],
    stopwords: [
      "a",
      "an",
      "and",
      "are",
      "as",
      "at",
      "be",
      "by",
      "for",
      "from",
      "how",
      "in",
      "is",
      "it",
      "of",
      "on",
      "or",
      "that",
      "the",
      "this",
      "to",
      "we",
      "with",
      "you",
      "your"
    ]
  };
})(globalThis);
