(function (root) {
  const App = (root.AIScriptDetector = root.AIScriptDetector || {});

  App.patterns = {
    scriptIntroPhrases: [
      "in today's video",
      "in this video",
      "today we're going to",
      "today i want to",
      "let's dive in",
      "without further ado",
      "here's why",
      "we're going to break down",
      "let's get into it",
      "today we'll cover",
      "welcome back to the channel",
      "before we get started",
      "if you've ever wondered",
      "watch until the end",
      "today i'm going to show you",
      "in this script",
      "in this breakdown"
    ],
    callToActionPhrases: [
      "like and subscribe",
      "hit that subscribe button",
      "leave a comment",
      "drop a comment",
      "thanks for watching",
      "follow for more",
      "stay tuned",
      "see you in the next one",
      "let me know what you think",
      "smash the like button",
      "subscribe to the channel",
      "ring the bell",
      "comment below",
      "share this video"
    ],
    recapPhrases: [
      "to recap",
      "in summary",
      "the bottom line",
      "the key takeaway",
      "wrapping up",
      "in conclusion",
      "all in all",
      "to sum it up"
    ],
    youtubePackagingPhrases: [
      "and now",
      "or die",
      "one by one",
      "while they try to",
      "find a way to stop",
      "find a way to survive",
      "find a way to escape",
      "forced to",
      "must survive",
      "must escape",
      "must pass",
      "before it's too late",
      "movie recap",
      "film recap",
      "story recap",
      "ending explained",
      "plot summary",
      "explained in minutes",
      "tries to survive",
      "has to survive"
    ],
    highStakesTerms: [
      "must",
      "die",
      "death",
      "survive",
      "escape",
      "killer",
      "kill",
      "killed",
      "cursed",
      "curse",
      "trapped",
      "forced",
      "haunted",
      "demise",
      "chased",
      "before"
    ],
    titleHookRegexes: [
      /\b(?:he|she|they)\b[\w\s,'-]{0,80}\band now\b[\w\s,'-]{0,80}\b(?:must|has to|needs to|is forced to)\b/i,
      /\b(?:must|has to|needs to|is forced to)\b[\w\s,'-]{0,60}\b(?:or die|to survive|before it's too late)\b/i,
      /\b(?:one by one|while they try to|find a way to (?:stop|survive|escape)|future demise)\b/i
    ],
    transitionPhrases: [
      "moreover",
      "furthermore",
      "additionally",
      "however",
      "therefore",
      "overall",
      "ultimately",
      "meanwhile",
      "in addition",
      "for example",
      "on the other hand",
      "as a result",
      "that said",
      "with that in mind"
    ],
    genericPhrases: [
      "it is important to note",
      "plays a crucial role",
      "in today's fast-paced world",
      "game changer",
      "take it to the next level",
      "across the board",
      "unlock the potential",
      "wide range of",
      "various aspects of",
      "for businesses and individuals alike",
      "from start to finish",
      "at the end of the day",
      "when it comes to",
      "one of the most important things",
      "the good news is",
      "the reality is",
      "you won't believe",
      "this is huge",
      "everything you need to know",
      "the secret to",
      "what most people don't realize"
    ],
    vagueTerms: [
      "various",
      "numerous",
      "significant",
      "innovative",
      "effective",
      "powerful",
      "robust",
      "seamless",
      "valuable",
      "meaningful",
      "dynamic",
      "transformative",
      "insightful",
      "remarkable",
      "comprehensive",
      "notable",
      "key",
      "crucial",
      "important",
      "impactful",
      "relevant",
      "helpful",
      "useful"
    ],
    hedgeTerms: [
      "generally",
      "often",
      "typically",
      "usually",
      "in many ways",
      "can help",
      "can improve",
      "may lead to",
      "tends to",
      "in some cases",
      "for many people",
      "in a lot of cases",
      "the truth is",
      "chances are"
    ],
    businessBuzzwords: [
      "solution",
      "strategy",
      "leverage",
      "optimize",
      "synergy",
      "landscape",
      "ecosystem",
      "framework",
      "scalable",
      "streamline",
      "efficiency",
      "stakeholders",
      "workflow",
      "alignment",
      "competitive",
      "engagement",
      "growth",
      "outcomes",
      "value",
      "audience",
      "content",
      "best practices"
    ],
    abstractTerms: [
      "innovation",
      "impact",
      "value",
      "growth",
      "efficiency",
      "strategy",
      "success",
      "potential",
      "approach",
      "process",
      "experience",
      "solution",
      "insight",
      "opportunity",
      "challenge",
      "benefit",
      "vision",
      "trend",
      "industry",
      "audience",
      "journey",
      "landscape",
      "improvement",
      "result",
      "outcome"
    ],
    // Multi-word constructions that assistant-drafted scripts lean on heavily and
    // spontaneous speakers rarely produce.
    assistantPhrases: [
      "in today's fast-paced world",
      "in today's digital age",
      "in today's world",
      "ever-evolving landscape",
      "rich tapestry",
      "a testament to",
      "stands the test of time",
      "play a pivotal role",
      "plays a pivotal role",
      "played a pivotal role",
      "plays a crucial role",
      "play a crucial role",
      "it's important to note",
      "it is important to note",
      "it's worth noting",
      "it is worth noting",
      "it's essential to",
      "it is essential to",
      "first and foremost",
      "unlock your full potential",
      "unlock the full potential",
      "unlock your potential",
      "embark on",
      "delve into",
      "dive deep",
      "deep dive into",
      "let's explore",
      "harness the power",
      "a myriad of",
      "a plethora of",
      "in essence",
      "in conclusion",
      "in summary",
      "serves as a reminder",
      "a powerful reminder",
      "a stark reminder",
      "one thing is clear",
      "the answer lies in",
      "have you ever wondered",
      "but what if",
      "so what are you waiting for",
      "whether you're a",
      "whether you are a",
      "something for everyone",
      "leaves a lasting impression",
      "hidden gems",
      "shrouded in mystery",
      "sent shockwaves",
      "a game changer",
      "take it to the next level",
      "elevate your",
      "the journey of",
      "on this journey",
      "a journey through",
      "is not just about",
      "isn't just about",
      "navigate the challenges",
      "navigate the complexities",
      "in a world where",
      "imagine a world",
      "you're not alone",
      "makes all the difference",
      "make all the difference",
      "endless possibilities",
      "peace of mind",
      "well on your way",
      "your future self",
      "at its core",
      "it's no secret",
      "look no further",
      "a must-visit",
      "shrouded in",
      "in the heart of",
      "not only that",
      "the bottom line is",
      "remember, ",
      "stay curious"
    ],
    // Single words over-represented in assistant prose. Counted per word, so each
    // adds only a little evidence on its own.
    assistantWords: [
      "delve",
      "delves",
      "tapestry",
      "testament",
      "multifaceted",
      "meticulous",
      "meticulously",
      "paramount",
      "pivotal",
      "intricate",
      "seamless",
      "seamlessly",
      "vibrant",
      "bustling",
      "nestled",
      "embark",
      "elevate",
      "elevates",
      "harness",
      "foster",
      "fosters",
      "resonate",
      "resonates",
      "realm",
      "unwavering",
      "indelible",
      "myriad",
      "plethora",
      "captivating",
      "enchanting",
      "breathtaking",
      "unforgettable",
      "transformative",
      "invaluable",
      "empower",
      "empowers",
      "unlock",
      "unleash",
      "streamline",
      "leverage",
      "cornerstone",
      "prowess",
      "ingenuity",
      "unparalleled",
      "exceptional",
      "stunning",
      "immerse",
      "thrive",
      "essential",
      "crucial",
      "fascinating",
      "remarkable",
      "cutting-edge",
      "ever-evolving",
      "moreover",
      "furthermore",
      "additionally",
      "ultimately",
      "overall",
      "incredible",
      "incredibly",
      "amazing",
      "iconic",
      "impressive",
      "extraordinary",
      "truly",
      "unique",
      "marvel",
      "resilience",
      "triumph",
      "legacy",
      "inspire",
      "inspiring",
      "determination",
      "standout",
      "mind-blowing",
      "timeless",
      "profound",
      "enhance",
      "enhances",
      "ensure",
      "ensures",
      "optimal",
      "vital",
      "notably",
      "showcase",
      "showcasing",
      "boasting",
      "boasts",
      "renowned",
      "journey"
    ],
    assistantRegexes: [
      /\b(?:not|more than|isn'?t|wasn'?t) (?:just|only|simply|merely) (?:a |an |about )?[\w\s'-]{1,40}[;,.:]\s*(?:it|this|that|they|he|she)(?:'s| is| was| are| were)\b/i,
      /\bwhether you'?re\b[^.?!]{1,80}\bor\b/i,
      /\bnumber (?:one|two|three|four|five|six|seven|eight|nine|ten|\d{1,2})\s*[:.]/i,
      /\b(?:a|the) (?:story|tale|testament|symbol|marvel|reminder) of\b/i,
      /\b(?:continues?|continuing) to (?:inspire|shape|captivate|resonate|fascinate)\b/i,
      /\b(?:anything is possible|the possibilities are endless)\b/i,
      /\b(?:which|what) [\w\s]{1,40}(?:surprised|inspired|fascinated) you (?:the )?most\b/i,
      /\b(?:tip|step|reason|habit|rule|secret) (?:number )?(?:one|two|three|four|five|1|2|3|4|5)\b/i,
      /\bfirst,[\s\S]{1,400}\bnext,[\s\S]{1,400}\bfinally,/i
    ],
    // Markers of unscripted speech: fillers, hedges, self-corrections, and
    // conversational glue that generated scripts almost never contain.
    spontaneityMarkers: [
      "um",
      "uh",
      "erm",
      "hmm",
      "gonna",
      "wanna",
      "gotta",
      "kinda",
      "sorta",
      "yeah",
      "yep",
      "nope",
      "okay so",
      "alright so",
      "you know",
      "i guess",
      "i think",
      "i don't know",
      "kind of",
      "sort of",
      "like a",
      "like the",
      "or something",
      "and stuff",
      "basically",
      "literally",
      "anyway",
      "no wait",
      "wait,",
      "oh no",
      "oh my god",
      "right, so",
      "let me just",
      "i'm not even joking",
      "to be fair",
      "which, ",
      "i'll be honest",
      "the hard way"
    ],
    stopwords: [
      "a",
      "an",
      "and",
      "are",
      "as",
      "at",
      "be",
      "by",
      "for",
      "from",
      "how",
      "in",
      "is",
      "it",
      "of",
      "on",
      "or",
      "that",
      "the",
      "this",
      "to",
      "we",
      "with",
      "you",
      "your"
    ]
  };
})(globalThis);
